apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: {name: final-devops-api, namespace: final-devops}
spec:
  selector: {matchLabels: {app: final-devops-api}}
  endpoints: [{port: http, path: /metrics, interval: 15s}]
