apiVersion: v1
kind: Service
metadata: {name: {{ include "final-devops.fullname" . }}-api}
spec:
  selector: {app: {{ include "final-devops.fullname" . }}}
  ports: [{name: http, port: 80, targetPort: 8080}]
